name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Check out code into dir
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t img .
    - name: Build the Docker image
      run: docker tag img 23923994/protoc-actions 
    - name: Docker Publish
      run: docker push docker.io/23923994/protoc-actions
